# Generated by Django 4.2.7 on 2023-11-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
